### ISSUE TITLE
Inconsistency between github repo learnstorybook-code and Create addons chapter of storybook tutorial

### ISSUE THREAD

**Issue by jchalmers100** [chromaui/learnstorybook-code#26] opened 2020-03-23 15:39 UTC
I've been through the tutorial as far as the end of Create Addons chapter, and have noticed that the repo code differs markedly in the '.storybook' folder from the actual tutorial code. I am trying to bring in the image assets to display them as shown in 'Displaying the actual assets' section, but can't figure out how to use a config.js file and addons.js file, which are present in this repo. I must have missed something because there is a marked difference between the two examples. 
Could you provide some explanation of how to display the image assets as shown?

**Comment by tmeasday** [comment] 2020-03-24 01:52
Hey @jchalmers100 apologies about this. I've had a TODO item to update this repo to bring it in line with Storybook 5.3 (which changed the `.storybook` directory a bit). The code snippets in the tutorial are correct AFAIK but these commits are not.

So if you follow the snippets in the code you should be OK. Is something not working?

**Comment by jchalmers100** [comment] 2020-03-24 16:31
Hi Tom, its fine actually. Its a good tutorial, but I'll have to study it again I think.

Thanks for the reply - that was useful


________________________________

**Comment by usrrname** [comment] 2020-10-12 22:15
I noticed a small difference today as I was making a demo for the repo with the intention to update the docs and codeblocks for angular... I see that on [the screens page](https://www.learnstorybook.com/intro-to-storybook/angular/en/screen/) the featured codeblock is for `pure-inbox-screen.component.ts`, however in the included in the video extract after "Cycling through states in Storybook makes it easy to test we’ve done this correctly:". [video here](https://www.learnstorybook.com/intro-to-storybook/finished-inboxscreen-states.mp4)

If you look closely, the title of the story is `InboxScreen` instead of `PureInboxScreen`. 
That leads me to wonder if they actually included `InboxScreenComponent` instead of `PureInboxScreen`, and was thus able to dispatch actions in the actions tab.

My code is [here](https://github.com/usrrname/learnstorybook-v6-angular) btw and @jonniebigodes  is reviewing it.

**Comment by jonniebigodes** [comment] 2020-10-15 19:16
@usrrname the video was a bit misleading, probably was kept from a previous version of the tutorial and spread around to the different versions of the tutorial. With the update to 6.0 i've added new ones and once the documentation is updated the issue will go away. Hopefully to a point where they can be safely removed from each tutorial and translation.

**Comment by usrrname** [comment] 2020-10-15 20:21
@jonniebigodes Thanks for your response. I thought I was going crazy as I tried to add `this.store.dispatch` to the `PureInboxScreen` and nothing fired or logged since it is actually AppComponent that contains `InboxScreen`, and PureInboxScreen is actually showing PureTaskList. Speaking of which, is it intended behaviour at this stage of the tutorial in the Storybook Canvas for `PureInboxScreen` for the dispatch to log?

ie. 
<img width="169" alt="Screen Shot 2020-10-15 at 3 41 06 PM" src="https://user-images.githubusercontent.com/6406037/96181739-76a7ed00-0f02-11eb-993c-0a26693a7119.png">

**Comment by jonniebigodes** [comment] 2021-07-15 22:45
Closing this as the Create addons chapter was removed from the Intro to Storybook to its own tutorial.

**Closed by jonniebigodes** 2021-07-15 22:45 UTC
